### PR TITLE
[VIVO-1949] - Fix external AGROVOC and LCSH service URLs

### PR DESCRIPTION
**Pull request by gneissone**
**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1949)**:  https://jira.lyrasis.org/browse/VIVO-1949

# What does this pull request do?
Updates the AGROVOC and LCSH service URLs to the updated URLs.

# What's new?
Very simple change. AGROVOC and LCSH now require 'https' instead of 'http' and return an error without it.

# How should this be tested?
Confirm issue by clicking the folder icon next to a person's 'Research Areas' field. Click add concept, ensure AGROVOC is selected, type in anything (e.g. 'carrot') and await the result that never comes.

Screen Shot 2021-01-25 at 3 49 10 PM

Apply fix, confirm you get results.

Screen Shot 2021-01-25 at 3 40 38 PM

Repeat for LCSH.

# Additional Notes:
N/A

# Interested parties
@VIVO-project/vivo-committers

### CODE REVIEW

**Review by awoods — APPROVED** [review]
Would you mind also targeting this PR against the `sprint-i18n` branch?

**Comment by gneissone** [comment]
> Would you mind also targeting this PR against the `sprint-i18n` branch?
I'm not sure how to submit a PR against multiple branches, is that possible? I guess I could open another PR that points at sprint-i18n.

**Comment by awoods** [comment]
It would either be another PR/branch, or just retarget this PR to `sprint-i18n`... since it is all ending up in `main` very soon.

**Comment by gneissone** [comment]
My commits were made to the main branch... I'd rather not start over or do any cherry picking to get it rebased to the sprint-i18n branch. Can we merge the current main branch into sprint-i18n? If so I will change this PR to point to sprint-i18n. Or if this PR gets a 2nd approval before the main -> sprint-i18n merge that works, too.

**Comment by awoods** [comment]
It appears that additional commits are not included in this PR, since it has been re-targeted from `main` to `sprint-i18`. 
I would suggest creating a new PR with just the two commits that you actually want:
- https://github.com/vivo-project/VIVO/pull/201/commits/d917ab5ae5ff70c2c09788712b25255228848ba8
- https://github.com/vivo-project/VIVO/pull/201/commits/30652f3a52c455dac01514ab3ddea5156a3903aa

**Comment by gneissone** [comment]
Superseded by https://github.com/vivo-project/VIVO/pull/213

**Pull request closed without merging**
