### PR TITLE
[VIVO-1930] - Update example.runtime.properties

### PR DESCRIPTION
**Pull request by gneissone**
See https://github.com/vivo-project/VIVO/pull/194 for details
https://jira.lyrasis.org/browse/VIVO-1930

### CODE REVIEW

**Comment by gneissone** [comment]
Not sure if this PR is going to play nice with https://github.com/vivo-project/VIVO/pull/197 due to https://github.com/vivo-project/VIVO/pull/197/files?file-filters%5B%5D=.n3&file-filters%5B%5D=.properties :/

**Comment by gneissone** [comment]
@awoods Feel like I'm chasing my tail a bit here, but I managed to merge the sprint-i18n-ized main back into this PR and should be ready for review again.

**Review by awoods — COMMENTED** [review]
For a cleaner PR, I simply cherry-picked your [functional commit](https://github.com/vivo-project/VIVO/pull/214/commits/7d5cb3719e16a2f29be515ad41e413a0af0a320d) over a branch current with `main`. This PR is now superseded by: https://github.com/vivo-project/VIVO/pull/222

**Comment by gneissone** [comment]
Superseded by https://github.com/vivo-project/VIVO/pull/222

**Pull request closed without merging**
