### PR TITLE
Added Bootstrap and updated CSS for Wilma theme to make it responsive

### PR DESCRIPTION
**Pull request by milospp**
**[GitHub issue 3910](https://github.com/vivo-project/VIVO/issues/3910)**
**[GitHub PR Vitro 429](https://github.com/vivo-project/Vitro/pull/429)**

# What does this pull request do?
Added bootstrap (only grid style) CSS and modified Wilma theme to leverage its responsive design feature and enhance the overall layout.

# What's new?
Mobile optimised desing
Avoided horizontal scroll

# How should this be tested?
Open every page and test by resizing up to around 400px in width (Mobile device toolbar can be used in google chrome to simulate phone display)

# Additional Notes:
Here is the video example

- The Left window is VIVO with old Wilma theme
- The middle window is a new, updated Wilma theme
- The right window is Tenderfoot theme (just for comparison)

[Video Example](https://youtu.be/9B0_cevrEeE)
https://youtu.be/9B0_cevrEeE

### CODE REVIEW

**Review by chenejac — CHANGES_REQUESTED** [review]
@milospp great work, it looks a lot of pages are responsive now in the case of using wilma theme. Can you please also check whether co-author network page (there is a link from a researcher profile page) and temporal graph page (there is a link from an organization profile page) can be also responsive in the case of small devices?

**Comment by rasteginas** [comment]
Hi, when loading the main page in the Firefox browser, the search button text is not in it's place.
ScreenshotMain

 I also noticed that the list of tabs is not displayed correctly, like in the Tenderfoot theme.
ScreenshotTabs

**Comment by milospp** [comment]
> Hi, when loading the main page in the Firefox browser, the search button text is not in it's place. ScreenshotMain
> 
> I also noticed that the list of tabs is not displayed correctly, like in the Tenderfoot theme. ScreenshotTabs

I changed the HTML of the search bar on the homepage, can you check again does it works now on Firefox? I wasn't able to reproduce the same bug.
Also, I fixed text wrapping in that menu ("View All" button)
When you build an app, clear the cache and hard reload the page (sometimes the browser caches old CSS files)

**Review by chenejac — DISMISSED** [review]
@milospp Works well for me (Google Chrome). Let's wait @rasteginas to check how it looks like in Firefox.

**Comment by rasteginas** [comment]
I tested the template. Looks good.

**Comment by chenejac** [comment]
@milospp bootstrap.min.js should be included in the code, some bootstrap java script functions are used in the extended search.

**Review by wwtamu — APPROVED** [review]

**Review by chenejac — APPROVED** [review]
@milospp well done, thanks

**Pull request merged**
