### PR TITLE
Uncomment missing language dependencies

### PR DESCRIPTION
**Pull request by gneissone**
**[Issue](https://github.com/vivo-project/VIVO/issues/3610)**: resolves https://github.com/vivo-project/VIVO/issues/3610

# What does this pull request do?
Re-adds language dependencies into pom.xml files. VIVO and Vitro languages must now always been included, even when using VIVO with a single language.

# How should this be tested?
Follow instructions on how to install VIVO at https://wiki.lyrasis.org/display/VIVODOC112x/Installing+VIVO. If VIVO installs and does not complain about missing language files or strings upon startup, it was a success. 

# Interested parties
@roflinn

### CODE REVIEW

**Review by litvinovg — APPROVED** [review]
Works good.

**Review by wwelling — APPROVED** [review]

**Review by roflinn — CHANGES_REQUESTED** [review]
Can we change the need in the Dockerfile to need the version number hardcoded?

Ideally update the logic that has the directory named with the version number.

**Comment by gneissone** [comment]
@roflinn I can pull that change out since it's really a separate issue. Something has changed in the pom files since the Dockerfile was created. Not sure what, but the Dockerfile broke due to the change in target directory name.

**Comment by gneissone** [comment]
@roflinn found the change that was breaking the Dockerfile and re-added a line in installer/home/pom.xml that was removed: `<finalName>${app-name}</finalName>`

**Pull request merged**
