### PR TITLE
[VIVO-1470] Cross-platform improvements for Maven

### PR DESCRIPTION
**Pull request by grahamtriggs**
https://jira.duraspace.org/browse/VIVO-1470

# What does this pull request do?
Small corrections to the pom.xml and assembly.xml files to improve cross-platform support - remove Windows warnings and resource character set problems.

# What's new?
UTF-8 properties in pom files to set character set for resource filtering.
Altered assembly output directory to not use a Unix convention.

# How should this be tested?
Rebuild the application, and ensure that all artefacts are created and deployed normally (e.g. there should be no visible change, other than the warnings no longer appearing on Windows)

# Additional Notes:
No documentation, dependency changes or other impact.

# Interested parties
@VIVO-project/vivo-committers

### CODE REVIEW

**Comment by brianjlowe** [comment]
The Windows-specific warnings are indeed gone from the console output of the build.  I can't confirm that the application still, runs, however, as the smoke test throws this:

FATAL: ApplicationImpl$ComponentsSetup
Can't connect to the database: VitroConnection.DataSource.url='jdbc:mysql://localhost/trunk', VitroConnection.DataSource.username='trunkuser'
edu.cornell.mannlib.vitro.webapp.application.ApplicationImpl$ComponentsSetup
java.sql.SQLException: The server time zone value 'GTB, or� de var�' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:489)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:69)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
	at com.mysql.cj.jdbc.ConnectionImpl.(ConnectionImpl.java:633)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at edu.cornell.mannlib.vitro.webapp.triplesource.impl.sdb.SDBConnectionSmokeTests.checkDatabaseConnection(SDBConnectionSmokeTests.java:96)
	at edu.cornell.mannlib.vitro.webapp.triplesource.impl.sdb.ContentTripleSourceSDB.startup(ContentTripleSourceSDB.java:102)
	at edu.cornell.mannlib.vitro.webapp.application.ApplicationImpl$ComponentsSetup.contextInitialized(ApplicationImpl.java:170)
	at edu.cornell.mannlib.vitro.webapp.startup.StartupManager.initialize(StartupManager.java:175)
	at edu.cornell.mannlib.vitro.webapp.startup.StartupManager.contextInitialized(StartupManager.java:65)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4716)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.cj.core.exceptions.InvalidConnectionAttributeException: The server time zone value 'GTB, or� de var�' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at com.mysql.cj.jdbc.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:118)
	at com.mysql.cj.mysqla.MysqlaSession.configureTimezone(MysqlaSession.java:293)
	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:2399)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1739)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)
	... 23 more

**Comment by grahamtriggs** [comment]
@brianjlowe That's a known "issue" independent of the build process, where the MySQL driver has a problem with the timezone reported by the database. There is another pull request that provides a default configuration on the connection string which will make that one go away.

**Comment by mconlon17** [comment]
Timezone issue is addressed by https://github.com/vivo-project/Vitro/pull/69 which provides a different version of the JDBC driver for MySql.

In the meantime, you can use jdbc:mysql://localhost/vitrodb?serverTimezone=UTC as the connection string

**Comment by gneissone** [comment]
@brianjlowe can you please try building and starting with the connection string Mike noted? The error you received is caused by the mysql connector which was upgraded in a [previous commit](https://github.com/vivo-project/Vitro/commit/4ba2f6ed3a56536c8bf0378aa799efa8c181bd87) and will be subsequently replaced in [PR 69](https://github.com/vivo-project/Vitro/pull/69).

**Pull request merged**
