### PR TITLE
[VIVO 1652] - Add vivo:AdministrativeUnit as a subclass of foaf:Organization

### PR DESCRIPTION
**Pull request by mconlon17**
**[VIVO-1652](https://jira.duraspace.org/browse/VIVO-1652)**

# What does this pull request do?
Adds a new class to the VIVO ontology -- AdministrativeUnit. Administrative  Unit is a part of an organization not otherwise identifiable as a department or school, college, etc.

Example:  The UF Health Science Center is an administrative unit (not a center)

AdministrativeUnit is not:
* a department.  We plan to add AdministrativeDepartment in the future.  AdministrativeDepartment is the counter part to AcademicDepartment and should clarify organizational representation in VIVO.
* an administrative unit of a country.  Wikipedia uses the term local administrative department to represent administrative divisions in countries not otherwise classified as states, counties, municipalities.  Administrative Unit is analogous for organizations. VIVO will likely add LocalAdministrativeUnit as a term for countries in the future.

# What's new?
* Changes to vivo.owl to define AdministrativeUnit in the VIVO ontology.
* Changes to vitroAnnotations.n3 to support use of AdministrativeUnit in the VIVO application.

# How should this be tested?
1. Build
1. Empty database (to force reread of vitroAnnotations.n3)
1. Start Tomcat
3. Use SysAdmin menu to add a new Administrative Unit (available under the Organizations heading)
1. Confirm new Administrative Unit in the Index under Organizations

# Additional Notes:
* The ontology file with its annotations serves as documentation.  The file can be opened in ontology tools and visualizers to see structure.
* When a new version of VIVO is released, the version of the ontology corresponding to the ontology is placed at http://vivoweb.org/ontology/core

# Interested parties
@VIVO-project/vivo-committers @vivo-project/contributors  @vivo-project/vivo-developers @mjaved495 @marijane @brianjlowe @tawahle

### CODE REVIEW

**Comment by marijane** [comment]
I am concerned about the fact that in most other ontologies, Administrative Unit refers to a place/geographical unit/territory/etc.
See https://lov.linkeddata.es/dataset/lov/terms?q=administrative+unit

Can we think of a better name?

**Comment by vioil** [comment]
I agree with MJW. Please let's come up with a different name. I can't think of anything useful

**Comment by marijane** [comment]
@hauschke you rattled off some German words for this concept in this morning's meeting.  I'd be interested to see a list of them and whether any of them might translate to English somehow.

**Comment by mconlon17** [comment]
Zentrale Einheiten  I think this may be closer to the US concept of Administrative Department.  Not sure.  In any case, different from what is being described here -- a unit that appears on an org chart.  Agree.  Name should be changed. Perhaps to a number :-)

**Comment by hauschke** [comment]
- Zentrale Einheiten oder Einrichtungen / central units or facilities
- Administrative Einheiten oder Einrichtungen / administrative units or facilities

Elena Liventsova proposed in https://serwiss.bib.hs-hannover.de/frontdoor/index/index/docId/803 to use Administrative Department and refers to Florida and Cornell for having Administrative Units  in use (p. 43, in German).

I'll ask in the German community for more feedback.

**Comment by hauschke** [comment]
In the VIVO-DE ontology it's central facility right now, and it includes IT departments, museums, or university archives and "...".

` <owl:Class rdf:about="http://vivoweb.org/ontology/core/de#ZentraleEinrichtung">
    <obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Rechenzentrum,
Universitätsarchiv, Museen ...</obo:IAO_0000112>`

https://github.com/VIVO-DE/vivo-de-ontology-extension/blob/master/ontology/vivo-de-0.3.rdf, line 126 to 128.

**Comment by mjaved495** [comment]
We were using a local class in Scholars@Cornell with the label :AdministrativeUnit . This included units such as Office of the President, Office of University Relations, Admissions and Financial Aids, Alumni Affairs and Development etc. We couldn't come up with any other reasonable label. We tried to keep distinction using two words "Administrative" vs "Academic". I wonder if there could be any third or fourth category (in the domain of a University).

I will not use terms such as "Central" or "Department" as part of the label. This may raise confusions.

**Comment by mconlon17** [comment]
Perhaps there are three kinds of things being described:

1. The AdministrativeDepartment.  Perhaps this could be called AdministrativeOrganization.
2. The CentralOrganization.  Not sure how to distinguish this from AdministrativeOrganization.
3. The PlaceholderOrganization.  The thing with a name, a place on an org chart (and perhaps a place on a campus) but with little other organizational stuff.  This was the idea for this pull request.  Seems different from an AdministrativeOrganization which would have budget, staff, leadership, function.

Labels are distinct from class names.  Labels should be the names people use.  The label "Academic Health Center" be on a PlaceholderOrganization.  The names of the classes convey too much information (and not enough -- nuance is lost).  People assume that a class such as "AdministrativeUnit" represents any of the three kinds of things.

**Comment by marijane** [comment]
Administrative Collective?
Administrative Aggregate?
Administrative Agglomerate?
Administrative Amalgamate?

Or does this need its own entity?  Maybe using something general like foaf:Organization would suffice?

**Comment by gneissone** [comment]
Reopening this pull request. In an effort to follow current best practices, the VIVO project will now be developed against the `master` branch. As a result of removing the `develop` branch, this pull request was automatically closed by GitHub, apologies for any confusion this may have caused.

**Pull request closed without merging**
