### PR TITLE
 Update license year

### PR DESCRIPTION
**Pull request by hauschke**

### CODE REVIEW

**Comment by fereira** [comment]
With Grahams departure at the end of 2017 I’m wondering who is responsible for merging PRs.  As a committer I “think” I could do it.  Should all committers get assigned as reviewers on a PR?  This is a no-brainer for a merge but I don’t want to step on any toes.

**Comment by gneissone** [comment]
Hi John,
Yes, I believe we all have the ability to merge PRs and I say it's safe for anyone to merge such small changes without any discussion. I'm not sure if there was ever a written policy. There is a voting process for code modifications described on the wiki but no guidance on what needs to be voted on. Maybe Mike can comment.

Benjamin




On Jan 8, 2018, at 07:17, John Fereira <notifications@github.com<mailto:notifications@github.com>> wrote:

With Grahams departure at the end of 2017 I’m wondering who is responsible for merging PRs. As a committer I “think” I could do it. Should all committers get assigned as reviewers on a PR? This is a no-brainer for a merge but I don’t want to step on any toes.

**Comment by mconlon17** [comment]
We're developing new processes.  We discussed today the normal requirement to have more than one person review each request.  I've reviewed this, as has John and Benjamin.  Let's have someone push the button.

**Comment by gneissone** [comment]
I push the button. Review process still not formalized but seems like we are coalescing on using the GitHub review feature and having multiple people give the thumbs up before merging.

**Pull request merged**
