### PR TITLE
VIVO-1963: Initial docker compose

### PR DESCRIPTION
**Pull request by wwelling**
[VIVO-1963](https://jira.lyrasis.org/browse/VIVO-1963)

Uses published [vivoweb/vivo-solr](https://hub.docker.com/repository/docker/vivoweb/vivo-solr) image created from Github Action of PR, https://github.com/vivo-project/vivo-solr/pull/4.

# What does this pull request do?

Provides docker-compose up for VIVO with docker network and Solr configuration.

# How should this be tested?

```
mvn clean install
docker-compose up
```

Navigate to http://localhost:8080 for VIVO and http://localhost:8983 for Solr

# Additional Notes:

`.env` file read by docker-compose. Currently, only has host VIVO home directory desired to be the source of volume.
`startup.sh` is the VIVO docker start command that templates runtime properties with Solr URL and then starts tomcat.

This will work with an existing VIVO home. Just have to make sure there is a digest file for it not to overwrite your files.

# Interested parties

@VIVO-project/vivo-committers

### CODE REVIEW

**Comment by delsborg** [comment]
@wwelling 
I've spun this up on my desktop with this commit: https://github.com/wwelling/VIVO/commit/3b2483fa071abe804d60221cc54ba9f79c9c70e7
So far so good.
Should I review the latest version?
Don

**Comment by wwelling** [comment]
@delsborg the latest version affords passing docker-compose environment, `.env`, variables into the entry point scripts. Specifically to afford reseting VIVO home and VIVO Solr core. Additionally, generating digest.md5 to preserve existing VIVO home on host machine if desired.

**Comment by delsborg** [comment]
> @delsborg the latest version affords passing docker-compose environment, `.env`, variables into the entry point scripts. Specifically to afford reseting VIVO home and VIVO Solr core. Additionally, generating digest.md5 to preserve existing VIVO home on host machine if desired.

@wwelling That's important for my use case. I will test that. Thanks

**Review by delsborg — APPROVED** [review]
Works great and as described.
Also, tested the interlink between the vivo-home volume which is on the host and mounted in the  container. 
Modified files such as the firsttime/menu.n3 and the results showed as soon as the container was rebooted.

Tested updates in the container, that also worked.

**Review by roflinn — APPROVED** [review]
I like! Also, it works with Windows Docker and PowerShell.

**Pull request merged**
