### PR TITLE
Add CollectionProcess and CurationProcess

### PR DESCRIPTION
**Pull request by mconlon17**
**[VIVO-1700](https://jira.lyrasis.org/browse/VIVO-1700)**:

Pull request addresses two issues:
* https://jira.lyrasis.org/browse/VIVO-1700 Collection Process
* https://jira.lyrasis.org/browse/VIVO-1699 Curation Process

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)

Thessen, AE, Woodburn, M, Koureas, D, Paul, D, Conlon, M, Shorthouse, DP and Ramdeen, S. 2019. Proper Attribution for Curation and Maintenance of Research Collections: Metadata Recommendations of the RDA/TDWG Working Group. Data Science Journal, 18: 54, pp. 1–11. DOI: https://doi.org/10.5334/dsj-2019-054

# What does this pull request do?
Adds two new classes to the VIVO ontology: CurationProcess and CollectionProcess 

# What's new?

To represent that Jane is the Collector of a particular Collection z, we say Jane has a CollectorRole, the role is realized in the CollectionProcess that has the Collection as output.

Usage:

    w a person
    x a CollectionRole
    y a CollectionProcess
    z a Collection

    w bearer of x
    x realized in y
    y has output z

# How should this be tested?

VIVO does not typically display processes in the UI.  SPARQL can be used to see that the class and its attributes have been added to the triple store.

# Additional Notes:
The VIVO software does not refer to CollectionProcess nor to CurationProcess.  These additions are to the ontology only.

# Interested parties
@vivo-project/vivo-ontologists

### CODE REVIEW

**Comment by diatomsRcool** [comment]
Should we have a separate Collection and Curation process for specimens/samples and (MaterialEntity) and actual data (InformationContentEntity)?

**Comment by mconlon17** [comment]
I've updated the pull request by removing the class expressions from CollectionProcess and CurationProcess

**Comment by gneissone** [comment]
Reopening this pull request. In an effort to follow current best practices, the VIVO project will now be developed against the `master` branch. As a result of removing the `develop` branch, this pull request was automatically closed by GitHub, apologies for any confusion this may have caused.

**Comment by diatomsRcool** [comment]
Thanks for reviewing! Can I get an ETA on the second review?

**Comment by awoods** [comment]
> Thanks for reviewing! Can I get an ETA on the second review?

@brianjlowe ? @marijane ? @gneissone ?

**Comment by gneissone** [comment]
> > Thanks for reviewing! Can I get an ETA on the second review?
> 
> @brianjlowe ? @marijane ? @gneissone ?

@marijane can you please review the revised pull request? I don't see any ill effects happening in the application but as it's an ontology change I'd prefer to leave the approval to those who work with the ontology :)

**Pull request merged**
