### PR TITLE
I18n vivo 1936

### PR DESCRIPTION
**Pull request by bkampe**
Updated the language comment in runtime.properties and restored the default values of example.settings.xml

### CODE REVIEW

**Comment by gneissone** [comment]
The compare in this PR is wonky. I'm not sure what's going on... it's showing files as changed when those changes have already been merged into sprint-i18n, and it's not showing the reversion to example-settings.xml (i.e. the compare seems stuck on an old commit).

**Comment by bkampe** [comment]
How is best to proceed here, should i close this PR and try to create a new one?

**Comment by gneissone** [comment]
> How is best to proceed here, should i close this PR and try to create a new one?

That's the easiest solution I can think of. Before making changes, make sure you have checked out the sprint-i18n branch, and performed `git pull` to make sure you have the latest code. Drop in the old example-settings.xml file and commit the change. Hopefully the diff is clean at that point.

**Comment by bkampe** [comment]
another try:
https://github.com/vivo-project/VIVO/pull/210

**Pull request closed without merging**
