### PR TITLE
Update example.runtime.properties

### PR DESCRIPTION
**Pull request by awoods**
See #194 for details

Resolves: https://jira.lyrasis.org/browse/VIVO-1930

### CODE REVIEW

**Comment by awoods** [comment]
Supersedes: https://github.com/vivo-project/VIVO/pull/214

**Comment by brianjlowe** [comment]
Looks great.  My only question is whether it would be more consistent to comment out the (empty) SMTP/replyTo properties rather than leaving them uncommented with empty values.

**Comment by gneissone** [comment]
> Looks great. My only question is whether it would be more consistent to comment out the (empty) SMTP/replyTo properties rather than leaving them uncommented with empty values.

If I recall correctly VIVO complains if the properties are missing. Let's see if my memory is correct...

**Review by brianjlowe — DISMISSED** [review]

**Comment by gneissone** [comment]
@awoods Just occurred to me we should update this value, too https://github.com/vivo-project/VIVO/blob/52139befe81c844aabc66007b26bb0c21e5485ea/home/src/main/resources/config/default.runtime.properties#L191

es_GO doesn't exist for VIVO anymore, correct? I imagine the logic for using the non-standard locale is still in the source, but the language files have been renamed to just 'es' if I recall correctly.

**Comment by awoods** [comment]
> @awoods Just occurred to me we should update this value, too
> 
> https://github.com/vivo-project/VIVO/blob/52139befe81c844aabc66007b26bb0c21e5485ea/home/src/main/resources/config/default.runtime.properties#L191
> 
> es_GO doesn't exist for VIVO anymore, correct? I imagine the logic for using the non-standard locale is still in the source, but the language files have been renamed to just 'es' if I recall correctly.

Since that will require additional testing, let's keep the scope of this set of PRs constrained... and revisit `es_GO` as a follow-on activity.

**Review by brianjlowe — APPROVED** [review]

**Comment by awoods** [comment]
@gneissone : since both you and I have fingerprints on this PR, it would be nice if someone else performed the "squash/merge".

**Pull request merged**
