### PR TITLE
adding collections process terms

### PR DESCRIPTION
**Pull request by diatomsRcool**
**Thank you for submitting a pull request! Title this pull request with a brief description of what the pull request fixes/improves/changes. Please describe the pull request in detail using the template below.**
* * *

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
Adding terms for issues 760-763 in vivo-isf-ontology repo
Moving two terms adding for issues 758 and 759 in vivo-isf-ontology repo

# What does this pull request do?
This PR adds terms needed for the RDA/TDWG attribution standard. The terms are related to giving credit for collections management.

# What's new?

- Collection Process and Curation Process are now subclasses of planned process. This is in line with how this is represented in OBI and in BCO.
- Terms from BCO and OBI have been added where appropriate as subclasses of either Collection process or Curation process as appropriate.
- New terms have been created where needed.

# How should this be tested?
Not sure...

# Additional Notes:
I think the added BCO terms are the first time a BCO term is used in VIVO 

# Interested parties
Would like to hear from @dshorthouse @qgroom and @ramonawalls @VIVO-project/vivo-committers

### CODE REVIEW

**Comment by awoods** [comment]
There appear to be many formatting and potentially unintended updates in this pull-request:

**Comment by diatomsRcool** [comment]
Changes made!

**Comment by awoods** [comment]
@diatomsRcool : wow... so much nicer. @mconlon17 / @brianjlowe , interested in reviewing?

**Comment by diatomsRcool** [comment]
The workshop that I need these terms for is happening first thing Thursday morning. Any chance this PR can get merged before then?

**Comment by ramonawalls** [comment]
Let me know if there are any BCO issues that need to be fixed.

**Comment by awoods** [comment]
> The workshop that I need these terms for is happening first thing Thursday morning. Any chance this PR can get merged before then?

@diatomsRcool : I am adding this to today's Development call to see if we can get a review/merge. If you have the time, please feel free to join:
https://wiki.lyrasis.org/display/VIVO/2020-09-22+-+VIVO+Development+IG

**Comment by awoods** [comment]
@mconlon17 ? @brianjlowe ? @roflinn ? any chance for a quick review/merge prior to @diatomsRcool 's Thursday workshop?

**Review by brianjlowe — CHANGES_REQUESTED** [review]
This looks good to go, with one exception:  the catalog-v001.xml file should be removed from this pull request, as the application will not expect to find such a file in a filegraph directory.  With that change, I would say that we can go ahead and merge.

**Comment by diatomsRcool** [comment]
file has been deleted

**Review by brianjlowe — APPROVED** [review]

**Review by awoods — APPROVED** [review]

**Pull request merged**
